version: "3.8"
services:
  dev:
    image: "${IMAGE}"
    container_name: "${CONTAINER}"
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    external_links:
      - mongo

  deploy:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    image: "${DEPLOYMENT_IMAGE}"
    container_name: "${CONTAINER}"
    external_links:
      - mongo

  npm:
    build:
      context: .
      dockerfile: Dockerfile
    image: "${IMAGE}"
    container_name: "${CONTAINER}"

  seed:
    image: "${IMAGE}"
    container_name: "${CONTAINER}"
    env_file:
      - .env
    build:
      context: .
      dockerfile: deploy.Dockerfile
    command: "npm run seed"
    ports:
      - "5000:5000"
    external_links:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
    external:
      name: aqs_mongodb_data
